services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  backend:
    image: fusionhs/hackathon-llm-product-api:0.0.3-SNAPSHOT
    environment:
      - 'HUGGINGFACE_API_KEY=<api-key>'
      - 'SPRING_PROFILES_ACTIVE=docker'
    depends_on:
      - postgres
    ports:
      - 8080:8080
