spring:
  application:
    name: product-api
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      lifecycle-management: start_only
llm:
  image-to-text:
    models:
      - group: Salesforce
        model: blip-image-captioning-base
      - group: Salesforce
        model: blip-image-captioning-large
      - group: nlpconnect
        model: vit-gpt2-image-captioning
      - group: moranyanuka
        model: blip-image-captioning-large-mocha
  prompt-select:
    models:
      - group: openai
        model: clip-vit-large-patch14

